swagger: "2.0"
info:
  version: "1.0.0"
  title: "API Documentation of MIE"
basePath: "/"
schemes:
  - "http"
  - "https"
paths:
  /api/v1/login:
    post:
      summary: "User login"
      consumes:
        - "application/json"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            type: "object"
            properties:
              email:
                type: "string"
                description: "The email of the user."
              password:
                type: "string"
                description: "The password of the user."
      responses:
        200:
          description: "Success"
          schema:
            type: "object"
            properties:
              token:
                type: "string"
                description: "The authentication token for the user."
        401:
          description: "Unauthorized"
        500:
          description: "Internal Server Error"

  /api/v1/needs:
    post:
      summary: "Create a new need"
      consumes:
        - "multipart/form-data"
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          type: "string"
          description: "Authorization token (Bearer token)"
        - name: "NeedIs"
          in: "formData"
          required: true
          type: "string"
          description: "Describe your need"
        - name: "Title"
          in: "formData"
          required: true
          type: "string"
          description: "The title of the need."
        - name: "ContactPerson"
          in: "formData"
          required: true
          type: "string"
          description: "The name of the contact person for the need."
        - name: "Keywords"
          in: "formData"
          required: true
          type: "string"
          description: "Keywords for the need."
        - name: "Proposal"
          in: "formData"
          required: true
          type: "string"
          description: "Proposal for the need."
        - name: "Solution"
          in: "formData"
          required: true
          type: "string"
          description: "Solution for the need."                              
        - name: "FileData"
          in: "formData"
          type: "file"
          description: "This is an optional file attachment for the need."
      responses:
        200:
          description: "Success"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                description: "The ID of the newly created need."
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        500:
          description: "Internal Server Error"