swagger: '2.0'
info:
  version: "1.0.0"
  title: "Download the file of need using id"
basePath: "/"
schemes:
  - "http"
paths:
    /api/v1/download/{id}:
      get:
        summary: Download the file of a need
        parameters:
          - in: path
            name: id
            description: ID of the need to have the url of the file
            required: true
            type: "integer"
        responses:
          200:
            description: OK
            schema:
              type: file
          404:
            description: File/Need not found
            schema:
              type: object
              properties:
                message:
                  type: "string"
