swagger: "2.0"
info:
  version: "1.0.0"
  title: "API Documentation of MIE"
basePath: "/"
schemes:
  - "http"
  - "https"

paths:
  /api/v1/download/{id}:
    get:
      tags:
        - Need Routes
      summary: "Download the file of a need"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: 'Authorization token (Bearer token)'
        - in: path
          name: id
          description: 'ID of the need to have the URL of the file'
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
          schema:
            type: file
        404:
          description: 'File/Need not found'
          schema:
            $ref: '#/definitions/Error'
        403:
          description: 'Invalid token'
        401:
          description: 'Unauthorized, no token provided'
definitions:
  DownloadFileRequest:
    type: object
    properties:
      Authorization:
        type: string
        description: 'authentication token for the user'
      id:
        type: integer
  DownloadFileResponse:
    type: object
    properties:
      file:
        type: file
  Error:
    type: object
    properties:
      message:
        type: string
