swagger: "2.0"
info:
  version: "1.0.0"
  title: "API Documentation of MIE"
basePath: "/"
schemes:
  - "http"
  - "https"

paths:
  /api/v1/login:
    post:
      tags:
        - User Routes
      summary: "User login"
      consumes:
        - 'application/json'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      responses:
        200:
          description: 'Success'
          schema:
            $ref: '#/definitions/LoginResponse'
        403:
          description: 'Invalid token'
        401:
          description: 'Unauthorized, no token provided'
        500:
          description: 'Internal Server Error'
definitions:
  LoginRequest:
    type: object
    properties:
      email:
        type: string
        description: 'email of the user.'
      password:
        type: string
        description: 'password of the user.'
  LoginResponse:
    type: object
    properties:
      token:
        type: string
        description: 'authentication token for the user'
