swagger: "2.0"
info:
  version: "1.0.0"
  title: "API Documentation of MIE"
basePath: "/"
schemes:
  - "http"
  - "https"

paths:
  /api/v1/profile:
    get:
      tags:
        - User Routes
      summary: "Get user profile"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: 'Authorization token (Bearer token)'
      responses:
        200:
          description: 'OK'
          schema:
            type: object
            properties:
              id:
                type: integer
              email:
                type: string
              profession:
                type: string
              iat:
                type: integer
              exp:
                type: integer
        403:
          description: 'Invalid token'
        401:
          description: 'Unauthorized, no token provided'
        500:
          description: 'Internal Server Error'
definitions:
  UserProfileRequest:
    type: object
    properties:
      Authorization:
        type: string
        description: 'authentication token for the user'
  UserProfileResponse:
    type: object
    properties:
      id:
        type: integer
      email:
        type: string
      profession:
        type: string
      iat:
        type: integer
      exp:
        type: integer