swagger: "2.0"
info:
  version: "1.0.0"
  title: "API Documentation of MIE"
basePath: "/"
schemes:
  - "http"
  - "https"

paths:
  /api/v1/update/needs/{id}:
    put:
      tags:
        - Need Routes
      summary: "Update a need"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: 'Authorization token (Bearer token)'
        - name: id
          in: path
          description: 'ID of the need to update'
          type: integer
        - name: NeedIs
          in: formData
          type: string
          description: 'Describe your need'
        - name: Title
          in: formData
          type: string
          description: 'The title of the need'
        - name: ContactPerson
          in: formData
          type: string
          description: 'The name of the contact person for the need'
        - name: Keywords
          in: formData
          type: string
          description: 'Keywords for the need'
        - name: Proposal
          in: formData
          type: string
          description: 'Proposal for the need'
        - name: Solution
          in: formData
          type: string
          description: 'Solution for the need'                              
        - name: FileData
          in: formData
          type: file
          description: 'This is an optional file attachment for the need'
      responses:
        200:
          description: 'Success response'
          schema:
            $ref: '#/definitions/UpdateNeedResponse'
        500:
          description: 'Failed to update the need'
          schema:
            $ref: '#/definitions/Error'
        403:
          description: 'Invalid token'
        401:
          description: 'Unauthorized, no token provided'
definitions:
  UpdateNeedRequest:
    type: object
    properties:
      Authorization:
        type: string
        description: 'authentication token for the user'
      NeedIs:
        type: string
      Title:
        type: string
      ContactPerson:
        type: string
      Keywords:
        type: string
      Proposal:
        type: string
      Solution:
        type: string
      FileData:
        type: string
        format: binary
        description: 'any file'
  UpdateNeedResponse:
    type: object
    properties:
      message:
        type: string
  Error:
    type: object
    properties:
      error:
        type: string
